### PR TITLE
feature: Added css styling to the application

### PR DESCRIPTION
**Pull request by krishnaacharyaa**
# Summary of the PR
Hi @chinmaykunkikar I went trought the present project it lacked styling , so I took an initiative to make decent considerable enhancements in the UI which is very subtle and at the same time engaging, to the end user.  Merging this PR will enhance the user experience.

# Problems in the present design 
Presently in the code, the styling doesn't seem very attractive, and it is a little distorted especially when it comes to the image and the whole beer card itself which is very difficult for the user to navigate and keep up with the app. So I considered enhancing it the best way possible based on my current knowledge.
image

# My approach to solution 
I focused on how best the app can be presented to the user in the most effective and effortless way, So I came up with the idea of making the cards of fixed width and fixed image height so it looks pleasing to the eyes and more friendly in terms of finding the right beer which is searched. 

I have also added styling with regard to the alignment of all the components and complete page in general, I have aimed center alignment throughout the app, which ensures consistency. And to make it more friendly, I have added subtle hover animation which enhances the user engagement with the application 
image

 
 # Comparision
 
image

# Conclusion:
I sincerely hope that I was able to bring in some value to the project through this PR, Please feel free to ask me if there is any further queries, would be more than happy to answer.

### CODE REVIEW

**Comment by chinmaykunkikar** [comment]
Thanks for the PR @krishnaacharyaa, but I do have a few nits to pick here before merging the code.

1. First things first: **the PR itself**. The title and the description can make or break your PRs. _Think what the maintainer wants to see._ It's your chance to pitch to the maintainer of the project about your opinions about the code, your thought process about your solution, or why this project can use your particular feature that you have come up with. The maintainers of large projects seldom review code without proper explanation of it. So take advantage of that. It's easier than it sounds.
In this case, please elaborate the description. Tell me the problems you found in the earlier design. Any particular thing that you didn't like, or something that can cause problems in the future. Tell me what kind of styling you came up with. You can also take help of some visual aids, like add a screenshot of how the new changes look like.
All I can figure out from your description is that it's only for light mode theming. Well, I didn't want light/dark modes for this project in the first place. So it doesn't help the goals of my project. So, think, should I be reviewing the code any further?

2. **The Project's Code Formatting Conventions:** Never break the project's code style with your own formatting style. ALways align with the existing style. For example, if you use `snake_case` for function and variable names whereas the rest of the project fully uses the `camelCase` as a convention. Here, I'm seeing that you are using tab spacing instead of the existing spaces spacing. It's almost an immediate turn off for the reviewer. _What happens here is: I am seeing the whole diff as changed even if 90% code is still the same._
In this particular case, I understand that it's my mistake that I didn't have any prettier config in place. Your vscode might have picked up your home style and formatted the document accordingly. So, what I am going to do is, add a prettier config now.
Reformat the two files according to these base style conventions.

**Comment by chinmaykunkikar** [comment]
Update: Done.
1. `cd` into the directory.
2. `git fetch`
3. Make sure you are still on the `styling` branch.
4. `git merge master`
5. You will have some merge conflict. Learn how to solve it if you don't know already. As a rule of thumb, always keep the changes of `upstream` (aka this repo) and ignore your changes for the time being.
6. After removing the merge conflict complete the merging (again, read about it thoroughly).
7. Do the formatting changes according to new prettier and eslint rules.
8. Commit and push

Then I will review your actual code :)

**Comment by krishnaacharyaa** [comment]
Hi @chinmaykunkikar thank you for your detailed comment on the perfect fixes about the PR, i have updated the comment tried to address all the comments.

_Just one observation_
I guess you missed appyling the prettier code configuration to the files , example  `"trailingComma": "all",` & ` "printWidth": 120,` which is reflected in my PR code diff

**Comment by chinmaykunkikar** [comment]
Thanks again for the PR, Krishna. Well done! The reason is clearly thought and written here, and the implementation of the solution looks good to me.

> _Just one observation_ I guess you missed appyling the prettier code configuration to the files , example `"trailingComma": "all",` & ` "printWidth": 120,` which is reflected in my PR code diff

That's a good catch! Thanks for updating the files.

Your "assignment" is done here :D 
Keep it up! And all the best with your journey ahead :) ✨

**Review by chinmaykunkikar — COMMENTED** [review]
LGTM!

**Comment by krishnaacharyaa** [comment]
Thank you Chinmay for your valuable information ✨
Any further tasks I would really be happy to take up, which would further shape me to the open source field
Thanks again🙂

**Pull request merged**
